NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
VERSION="2.0.0"

ACCOUNTS=[
  "GDSCUECSJ2UHOZJHSPXJEEXXQRRS5XQD62Y6XIGMFKQY5PBXNIJGXXRP"
]

[DOCUMENTATION]
ORG_NAME="LEXORA"
ORG_DBA="LEXORA"
ORG_DESCRIPTION="LEXORA ecosystem information and LEXO asset documentation."

[[CURRENCIES]]
code="LEXO"
issuer="GDSCUECSJ2UHOZJHSPXJEEXXQRRS5XQD62Y6XIGMFKQY5PBXNIJGXXRP"
name="LEXO"
desc="An ecosystem asset for Lexora."
status="live"
display_decimals=7
is_asset_anchored=false
